# Generated by Django 4.2.4 on 2023-08-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabla',
            name='edad',
        ),
        migrations.AddField(
            model_name='tabla',
            name='genero',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
